enforce using hash files and error out if missing

diff --git a/support/download/check-hash b/support/download/check-hash
--- a/support/download/check-hash
+++ b/support/download/check-hash
@@ -33,8 +33,8 @@ base="${3}"
 
 # Does the hash-file exist?
 if [ -z "${h_file}" -o ! -f "${h_file}" ]; then
-    printf "WARNING: no hash file for %s\n" "${base}" >&2
-    exit 0
+    printf "ERROR: no hash file for %s (%s) \n" "${base}" "${h_file}" >&2
+    exit 3
 fi
 
 # Check one hash for a file
